### ISSUE TITLE
issue in parseNodeId function in NodeId class

### ISSUE THREAD

**Issue by fatkhrus** [OPCFoundation/UA-Java-Legacy#192]
When parsing Numeric NodeID type in some reasons Identifier parses like Integer and not UnsignedInteger (according OPC UA Foundation specification) and when Identifier is greater than Integer maximum value (2,147,483,647) it raises exception.

**Comment by abhijit-malkhede** [comment]
Provided a fix for the issue.
Please refer raised PR #206.
PR has been merged by Jouni Aro.
