### ISSUE TITLE
Server certificate Validation

### ISSUE THREAD

**Issue by dreampangari** [OPCFoundation/UA-Java-Legacy#200]
Should client validate server certificate which it has received in  getEndpoint/createsession  call like expiry dates ,invalid certificate and trusted/untrusted?

**Comment by jouniaro** [comment]
Yes. The [DefaultCertificateValidator](https://github.com/OPCFoundation/UA-Java-Legacy/blob/master/src/main/java/org/opcfoundation/ua/cert/DefaultCertificateValidator.java) can help with that.
