### ISSUE TITLE
Bad_CommunicationError (code=0x80050000, description="2147811328, Read timed out")

### ISSUE THREAD

**Issue by gnraju20411** [OPCFoundation/UA-Java-Legacy#217]
if i run client and server on same machine both are communicate good.
when i publish the server on AWS instance (Ubuntu server)  getting the issue from client side?
what is the reason, please give me the information on the issue.
Exception in thread "main" org.opcfoundation.ua.common.ServiceResultException: Bad_CommunicationError (code=0x80050000, description="2147811328, Read timed out")

**Comment by jouniaro** [comment]
This is some kind of a communication problem between the client and server.
