### ISSUE TITLE
Is there support available for sending large message in chunks from opc-ua-stack jar

### ISSUE THREAD

**Issue by pradeipk** [OPCFoundation/UA-Java-Legacy#218]
Hello,
We have a requirement in our project, where we need to send a large number of items to write. So can you please confirm when
the request size goes beyond the MaxRequestMessageSize returned by OPC server then, whether opc-ua-stack jar breaks the request message into chunks and send it to the server?

**Comment by jouniaro** [comment]
No, it won't break the message to chunks for this, but generates an error, according to the specification.
