### ISSUE TITLE
How to share the real time data values in server?

### ISSUE THREAD

**Issue by Chuntianhong** [OPCFoundation/UA-Java-Legacy#223]
I should implement the OPC Server function in my JavaFX and should provide real-time data values in the clients request.
How can I share the real time data values in server?
Would you provide any sample?
Thank you for your help.

**Comment by jouniaro** [comment]
This project only implements the communication stack. For full applications, you will need to implement all the services as well. That it outside the scope of this project, but the Prosys OPC UA SDK for Java covers the full server implementation, for example.

If you wish to do it yourself, you can take a look at the ServerExample1, which shows a minimal implementation that you can start with. There is quite much to cover in total, so you may like to take a look at the SDK option as well, anyway.
